default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: expenses
  max_connections: 5

development:
  <<: *default

test:
  <<: *default

production:
  username: usipeuccrzcwdu
  password: 13H5sXf7rmoAoaA2PfJ_-4A1rW
